from __future__ import annotations

import pytest
from aie4ml.cost.listing import Loop, ScheduleUnavailable, loop_plan, wrapper_bundles

COMPILER = 'X-2025.06#865883355f#260312'


def _listing(tmp_path, *lines, compiler=COMPILER):
    """A tile listing whose kernel `run` holds `lines`: directives as given, anything else a bundle."""
    body = [line if line.startswith('.') else f'        1024    0x00 0x00 0x00 0x00      {line}' for line in lines]
    path = tmp_path / 'tile.lst'
    header = f'// File generated by darts version {compiler}, Sat Sep 26 07:13:41 2026'
    path.write_text('\n'.join(['', header, '.label _ZN6kernel3runEv', *body, '.label _ZN6kernel3runEv__end']))
    return path


def _nest(counter_init, inner='NOP'):
    # An outer software loop whose counter is spilled around a hardware loop that reuses its register.
    return (
        counter_init,
        '.loop_nesting 1',
        'ST r7, [sp, #-8]; MOV.s12 r7, #9',  # stores the counter: a bundle reads before it writes
        'MOV.s10 lc, #4',
        '.loop_nesting 2',
        '.begin_of_loop',
        inner,
        'NOP',
        '.end_of_loop',
        '.loop_nesting 1',
        'LDA.SPIL r7, [sp, #-8]',
        'BDEC r7, r7, cb0',
        '.loop_nesting 0',
        'RET lr',
    )


def test_loop_counts_are_traced_through_spills_and_hardware_loops(tmp_path):
    plan = loop_plan(_listing(tmp_path, *_nest('MOV.s12 r7, #2')), 'AIE')
    assert plan.cycles() == 2 + 3 * (4 + 4 * 2)


def test_the_descriptor_keeps_what_timing_needs_and_rebuilds_the_same_plan(tmp_path):
    inner = 'VLDA wr0, [p3], #32; VLDB wr1, [p3, cs4]; VMOV MCD, bm0'  # pairs on one buffer and writes a word
    plan = loop_plan(_listing(tmp_path, *_nest('MOV.s12 r7, #2', inner)), 'AIE')
    record = plan.root.record()
    assert record['items'][1]['items'][1]['items'] == ['pair+write', 1]
    assert Loop.from_record(record).record() == record
    assert plan.root.pairs() == 3 * 4 and plan.root.moves_cascade()


def test_a_schedule_that_cannot_be_accounted_for_gives_no_cycles(tmp_path):
    with pytest.raises(ScheduleUnavailable, match='not one immediate'):
        loop_plan(_listing(tmp_path, *_nest('MOV r7, r3')), 'AIE')
    with pytest.raises(ScheduleUnavailable, match='not the one its previous iteration left'):
        loop_plan(_listing(tmp_path, *_nest('MOV.s12 r7, #2', 'VST wd0, [sp, #-32]')), 'AIE')  # reaches -8
    with pytest.raises(ScheduleUnavailable, match='AIE-ML listing form'):
        loop_plan(_listing(tmp_path, *_nest('MOV.s12 r7, #2')), 'AIE-ML')
    with pytest.raises(ScheduleUnavailable, match='compiler X-2026.06#0#0 has not been checked'):
        loop_plan(_listing(tmp_path, *_nest('MOV.s12 r7, #2'), compiler='X-2026.06#0#0'), 'AIE')
    plan = loop_plan(_listing(tmp_path, 'MOV.s12 r7, #2', 'BNEZ r7, #1024', 'RET lr'), 'AIE')
    with pytest.raises(ScheduleUnavailable, match='conditional'):
        plan.cycles()


def test_the_wrapper_cost_is_its_loop_around_the_call(tmp_path):
    def main(*body):
        path = tmp_path / 'main.lst'
        bundles = [line if line.startswith('.') else f'        1024    0x00 0x00      {line}' for line in body]
        path.write_text(
            '\n'.join(
                [
                    '',
                    f'// File generated by darts version {COMPILER}, now',
                    '.label _main',
                    *bundles,
                    '.label _main__end',
                ]
            )
        )
        return path

    setup = ('MOV r1, #0', '.loop_nesting 1', 'LDA r2, [p0]')
    per_call = ('.loop_nesting 2', 'ACQ #32, #1, r10', 'JAL #1008', 'NOP', 'REL #32, #1, r10', 'BNEZ r11, #480')
    assert wrapper_bundles(main(*setup, *per_call, '.loop_nesting 1', 'BNEZ r2, #416'), 'AIE') == 5
    with pytest.raises(ScheduleUnavailable, match='not straight-line'):
        wrapper_bundles(main(*setup, *per_call[:-1], 'BEQZ r3, #600', per_call[-1], '.loop_nesting 1'), 'AIE')
