"""A kernel's schedule, read from the AIE compiler's listing of its tile (`Work/aie/<tile>/Release/<tile>.lst`).

Counts the static issue cycles of `run` per call: every bundle, times the trip counts of the hardware and software
loops around it, each count traced by value to one immediate. Anything it cannot account for completely -- a call, a
conditional branch, an untraceable count, or a generation and compiler not checked against the simulator's
instruction profiles (`CHECKED`) -- refuses rather than guesses.
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple, Union

from ..device_catalog import load_device_catalog

# The generations and compilers (`compiler_version`) whose listings this parser was checked against: every loop
# count agreeing with the simulator's instruction profile.
CHECKED = frozenset(
    {
        ('AIE', 'V-2024.06#8be6237c82#250729'),  # Vitis 2025.2
        ('AIE', 'X-2025.06#865883355f#260312'),  # Vitis 2026.1 and 2026.1.1
    }
)

_COMPILER = re.compile(r'^// File generated by darts version (\S+),')
_BUNDLE = re.compile(r'^\s+(\d+)\s+(?:0x[0-9a-f]{2}\s+)+(.*)$')
_ENCODING = re.compile(r'^\s+\d+\s+((?:0x[0-9a-f]{2}\s+)+)')
_SECTION = re.compile(r'^\.(?:text|data|bss|rodata|section)\b')
_COPY = re.compile(r'^MOV\s+(\w+),\s*(\w+)$')
_SPILL = re.compile(r'^ST(?:\.SPIL)?\s+(\w+),\s*\[sp,\s*#(-?\d+)\]$')
_RELOAD = re.compile(r'^LD[AB]?(?:\.SPIL)?\s+(\w+),\s*\[sp,\s*#(-?\d+)\]$')
_SLOT = re.compile(r'\[sp,\s*#(-?\d+)\]')
_STACK_ACCESS = re.compile(r'\[sp(?:,\s*#-?\d+)?\]')  # sp as an address with a fixed offset, or moved itself
_POST_MODIFY = re.compile(r'\[(\w+)\],')  # [p0], #32: p0 moves on
_DESTINATION = re.compile(r'^\S+\s+\[?(\w+)')
_STORE = re.compile(r'^V?ST')
_CALL = re.compile(r'^(?:JL|JAL|CALL)\b')
_BRANCH = re.compile(r'^(?:BNEZ|BEQZ|BNE|BEQ|BLT|BGE|BLTU|BGEU|JNZ|JZ)\b')  # taken only sometimes
_JUMP = re.compile(r'^J\s+#')  # an unconditional jump: a loop back-edge without a counter
_NO_DESTINATION = re.compile(r'^(?:NOP|RET|J)\b')


@dataclass(frozen=True)
class Decoder:
    """What a generation's instructions mean, where they differ: setting a location to an immediate, the
    decrement-and-branch that closes a software loop (dst, src), the store forms that write fewer bytes than the
    generation's store unit (its `StoreBytes` in aie_devices.json), which instructions read or write the cascade,
    and a vector load with its base register (None where not yet known for the generation)."""

    immediate: re.Pattern
    decrement_branch: re.Pattern
    narrow: Tuple[Tuple[re.Pattern, int], ...] = ()
    cascade_read: Optional[re.Pattern] = None
    cascade_write: Optional[re.Pattern] = None
    vector_load: Optional[re.Pattern] = None


_ML_DECODER = dict(
    immediate=re.compile(r'^MOV(?:A|X|XM)?\s+(\w+),\s*#(-?\d+)$'),
    decrement_branch=re.compile(r'^JNZD\s+(\w+),\s*(\w+),'),
)
DECODERS = {
    'AIE': Decoder(
        immediate=re.compile(r'^MOV(?:\.[su]\d+)?\s+(\w+),\s*#(-?\d+)$'),
        decrement_branch=re.compile(r'^BDEC\s+(\w+),\s*(\w+),'),
        narrow=((re.compile(r'^VST(?:\.SPIL)?\.48\.SRSB\s+bm\d'), 16),),  # 16 accumulator lanes, a byte each
        cascade_read=re.compile(r',\s*SCD\b'),  # VMOV acc, SCD: one word from the chain's previous kernel
        cascade_write=re.compile(r'\bMCD\s*,'),  # VMOV MCD, acc: one word to the next
        vector_load=re.compile(r'^VLD[AB](?:\.[\w.]+)?\s+\w+,\s*\[(\w+)'),  # VLDA wr0, [p3, cs4]: base p3
    ),
    'AIE-ML': Decoder(**_ML_DECODER),
    'AIE-MLV2': Decoder(**_ML_DECODER),
}


def _stored_bytes(instruction: str, decoder: Decoder, store_bytes: int) -> int:
    """How many bytes a store writes: its generation's store unit width, unless a narrow form says fewer."""
    return next((size for form, size in decoder.narrow if form.match(instruction)), store_bytes)


class ScheduleUnavailable(RuntimeError):
    """The listing cannot be accounted for completely, so it gives no cycle count."""


# What timing needs of a bundle, '+'-joined: 'pair' -- two of its vector loads read one buffer, so they stall on its
# bank; 'read' / 'write' -- it moves a cascade word. An untagged bundle only issues.
TAGS = ('pair', 'read', 'write')


@dataclass
class Loop:
    """One loop the compiler kept (the root is the function body, run once): one iteration's bundles and the loops
    nested in it, in program order. A tagged bundle is its tags; untagged bundles are counted in runs."""

    depth: int
    hardware: bool = False
    trips: Optional[int] = None
    items: List[Union[int, str, 'Loop']] = field(default_factory=list)

    def add(self, tags: str) -> None:
        if not tags and self.items and isinstance(self.items[-1], int):
            self.items[-1] += 1
        else:
            self.items.append(tags or 1)

    @property
    def children(self) -> List['Loop']:
        return [item for item in self.items if isinstance(item, Loop)]

    def bundles(self) -> int:
        """Bundles of one iteration, its nested loops' aside."""
        return sum(item if isinstance(item, int) else 1 for item in self.items if not isinstance(item, Loop))

    def tagged(self, tag: str) -> int:
        """Bundles of one iteration tagged `tag`, its nested loops' aside."""
        return sum(tag in item.split('+') for item in self.items if isinstance(item, str))

    def cycles(self) -> int:
        """Static issue cycles of all its iterations."""
        return self.trips * (self.bundles() + sum(child.cycles() for child in self.children))

    def pairs(self) -> int:
        """Executions of a bundle whose loads pair on one buffer, over all its iterations."""
        return self.trips * (self.tagged('pair') + sum(child.pairs() for child in self.children))

    def moves_cascade(self) -> bool:
        return bool(self.tagged('read') or self.tagged('write')) or any(c.moves_cascade() for c in self.children)

    def record(self) -> Dict:
        """The schedule descriptor: loops, trips and tagged bundles in program order, without the code."""
        items = [item.record() if isinstance(item, Loop) else item for item in self.items]
        return {'hardware': self.hardware, 'trips': self.trips, 'items': items}

    @classmethod
    def from_record(cls, record: Dict, depth: int = 0) -> 'Loop':
        items = [cls.from_record(item, depth + 1) if isinstance(item, dict) else item for item in record['items']]
        return cls(depth, record['hardware'], record['trips'], items)


@dataclass
class LoopPlan:
    root: Loop
    conditional: bool

    def cycles(self) -> int:
        if self.conditional:
            raise ScheduleUnavailable('a conditional branch makes some regions run only sometimes.')
        return self.root.cycles()


# What a register or stack slot holds at a point of one iteration: an immediate, the value it held as that
# iteration of `frame` began (`_Carried`), or None when unknown.
@dataclass(frozen=True)
class _Carried:
    frame: '_Frame'
    location: str


class _Frame:
    """One loop while it is read: what each location holds so far in an iteration, and what it held as the loop
    was entered (its parent's values then)."""

    def __init__(self, loop: Loop, parent: Optional['_Frame']):
        self.loop, self.parent = loop, parent
        self.entry = dict(parent.values) if parent else {}
        self.values: Dict[str, object] = {}
        self.written = set()
        self.counter: Optional[str] = None  # the dst of this loop's BDEC, or 'lc' for a hardware loop

    def get(self, location: str):
        if location in self.values:
            return self.values[location]
        return _Carried(self, location) if self.parent else None

    def at_entry(self, location: str):
        if location in self.entry:
            return self.entry[location]
        return _Carried(self.parent, location) if self.parent and self.parent.parent else None

    def set(self, location: str, value) -> None:
        self.values[location] = value
        self.written.add(location)


def _run_function(lines: List[str]) -> List[str]:
    starts = [i for i, line in enumerate(lines) if line.startswith('.label _ZN') and 'runE' in line]
    begin = [i for i in starts if not lines[i].endswith('__end')]
    end = [i for i in starts if lines[i].endswith('__end')]
    if len(begin) != 1 or len(end) != 1:
        raise ScheduleUnavailable(f'the listing holds {len(begin)} kernel run functions, not one.')
    return lines[begin[0] : end[0]]


def run_code_hash(object_listing: Path) -> str:
    """Fingerprint of the machine code of the kernel `run` alone, from the object listing (`<tile>.o.lst`), where
    `run` sits in a section of its own before linking places it, so the same code hashes the same on any tile of
    any design. Helpers it calls and constant data are not in it: what invalidates a measurement is the
    specialization key, whose source fingerprint covers them."""
    lines = object_listing.read_text(errors='replace').splitlines()
    starts = [i for i, line in enumerate(lines) if line.startswith('.text') and 'runE' in line]
    if len(starts) != 1:
        raise ScheduleUnavailable(f'{object_listing} holds {len(starts)} kernel run sections, not one.')
    digest = hashlib.sha256()
    for line in lines[starts[0] + 1 :]:
        if _SECTION.match(line):
            break
        if match := _ENCODING.match(line):
            digest.update(match[1].encode())
    return digest.hexdigest()[:20]


def compiler_version(listing: Path) -> str:
    """The compiler that wrote a listing, as its header -- its first line with text -- names it."""
    with listing.open(errors='replace') as lines:
        match = _COMPILER.match(next((line for line in lines if line.strip()), ''))
    if match is None:
        raise ScheduleUnavailable(f'{listing} does not name the compiler that wrote it.')
    return match[1]


def wrapper_bundles(listing: Path, generation: str) -> int:
    """Bundles the kernel's wrapper (`main`) issues per call of `run`: its loop around the call, which acquires and
    releases the buffers' locks, picks each buffer's ping or pong half and calls `run`. Counted only when that loop
    is straight-line code closed by its one back-edge, with no loop inside."""
    compiler = compiler_version(listing)
    if (generation, compiler) not in CHECKED:
        raise ScheduleUnavailable(f'the {generation} listing form of compiler {compiler} has not been checked.')
    lines = listing.read_text(errors='replace').splitlines()
    if '.label _main' not in lines or '.label _main__end' not in lines:
        raise ScheduleUnavailable(f'{listing} holds no wrapper main.')
    regions: List[Tuple[int, List[List[str]]]] = [(0, [])]  # the bundles of each run of lines at one loop depth
    for line in lines[lines.index('.label _main') : lines.index('.label _main__end')]:
        if line.startswith('.loop_nesting'):
            regions.append((int(line.split()[1]), []))
        elif match := _BUNDLE.match(line):
            regions[-1][1].append([instruction.strip() for instruction in match[2].split(';')])
    calling = [(depth, bundles) for depth, bundles in regions if any(_CALL.match(i) for b in bundles for i in b)]
    if len(calling) != 1:
        raise ScheduleUnavailable(f'the wrapper calls from {len(calling)} places, not one.')
    depth, bundles = calling[0]
    branches = sum(bool(_BRANCH.match(i)) for b in bundles for i in b)
    if depth == 0 or branches != 1 or any(d > depth for d, _ in regions):
        raise ScheduleUnavailable('the wrapper loop around run is not straight-line code closed by one back-edge.')
    return len(bundles)


def loop_plan(listing: Path, generation: str) -> LoopPlan:
    """The loop plan of the kernel `run` in a tile's listing, compiled for `generation`."""
    compiler = compiler_version(listing)
    if (generation, compiler) not in CHECKED:
        raise ScheduleUnavailable(f'the {generation} listing form of compiler {compiler} has not been checked.')
    decoder = DECODERS[generation]
    store_bytes = int(load_device_catalog()['generations'][generation]['StoreBytes'])
    if decoder.cascade_read is None or decoder.cascade_write is None or decoder.vector_load is None:
        raise ScheduleUnavailable(f'the {generation} decoder does not know cascade accesses or vector loads.')
    root = Loop(depth=0, trips=1)
    frames = [_Frame(root, None)]
    closed = []
    conditional = False
    problems = []
    slots = set()

    def close() -> None:
        frame = frames.pop()
        if frame.counter is None:
            problems.append(f'a software loop at depth {frame.loop.depth} closes without a counter.')
        closed.append(frame)
        for location in frame.written:  # what the last iteration left, where that is an immediate
            left = frame.values[location]
            frames[-1].set(location, left if isinstance(left, int) else None)

    for line in _run_function(listing.read_text(errors='replace').splitlines()):
        if line.startswith('.loop_nesting'):
            depth = int(line.split()[1])
            while len(frames) - 1 > depth:
                close()
            while len(frames) - 1 < depth:
                loop = Loop(depth=len(frames))
                frames[-1].loop.items.append(loop)
                frames.append(_Frame(loop, frames[-1]))
        elif line.startswith('.begin_of_loop'):
            frames[-1].loop.hardware, frames[-1].counter = True, 'lc'
        elif match := _BUNDLE.match(line):
            instructions = [instruction.strip() for instruction in match[2].split(';')]
            frames[-1].loop.add(_tags(instructions, decoder))
            conditional |= any(_BRANCH.match(instruction) for instruction in instructions)
            if problem := _execute(instructions, frames[-1], slots, decoder, store_bytes):
                problems.append(problem)
    while len(frames) > 1:
        close()
    if problems and not conditional:  # a conditional branch is the root cause when both occur
        raise ScheduleUnavailable(problems[0])
    if not conditional:
        for frame in closed:
            start = _resolve(frame.at_entry(frame.counter))
            if start is None or start < 0:
                raise ScheduleUnavailable(f'the count of a loop at depth {frame.loop.depth} is not one immediate.')
            frame.loop.trips = start if frame.loop.hardware else start + 1
    return LoopPlan(root, conditional)


def _tags(bundle: List[str], decoder: Decoder) -> str:
    """A bundle's tags (`TAGS`). Two vector loads off one base register read one buffer; off the stack pointer they
    are not counted: stack pairs were seen to stall only where another buffer shares the stack's bank."""
    bases = [match[1] for instruction in bundle if (match := decoder.vector_load.match(instruction))]
    bases = [base for base in bases if base != 'sp']
    tags = ['pair'] if len(bases) != len(set(bases)) else []
    tags += [
        kind
        for kind, form in (('read', decoder.cascade_read), ('write', decoder.cascade_write))
        if any(form.search(instruction) for instruction in bundle)
    ]
    return '+'.join(tags)


def _execute(bundle: List[str], frame: _Frame, slots: Set[int], decoder: Decoder, store_bytes: int) -> Optional[str]:
    """Track what one bundle writes; a problem, if it makes the loop count untraceable. All its instructions read
    their operands before any of them writes. `slots` are the stack offsets spilled to so far: a store clobbers
    every one its bytes may reach."""
    written = []
    counter = None
    for instruction in bundle:
        if re.search(r'\bsp\b', _STACK_ACCESS.sub('', instruction)):
            return f'the stack address escapes into a register at depth {frame.loop.depth}: {instruction!r}.'
        if _CALL.match(instruction):
            raise ScheduleUnavailable(f'run calls out: {instruction!r}.')
        if _JUMP.match(instruction):
            return f'a loop at depth {frame.loop.depth} jumps back without a counter.'
        if match := decoder.decrement_branch.match(instruction):
            dst, src = match.groups()
            if frame.counter is not None:
                return f'a loop at depth {frame.loop.depth} decrements two counters.'
            if frame.get(src) != _Carried(frame, dst):
                return f'loop counter {src} at depth {frame.loop.depth} is not the one its previous iteration left.'
            counter = dst
            written.append((dst, None))
        elif match := decoder.immediate.match(instruction):
            written.append((match[1], int(match[2])))
        elif match := _COPY.match(instruction):
            written.append((match[1], frame.get(match[2])))
        elif match := _RELOAD.match(instruction):
            written.append((match[1], frame.get(f'sp{match[2]}')))
        elif _STORE.match(instruction):
            if match := _SLOT.search(instruction):
                offset, spill = int(match[1]), _SPILL.match(instruction)
                width = 4 if spill else _stored_bytes(instruction, decoder, store_bytes)
                written += [(f'sp{slot}', None) for slot in slots if offset - 4 < slot < offset + width]
                if spill:
                    written.append((f'sp{offset}', frame.get(spill[1])))
                    slots.add(offset)
        elif not _NO_DESTINATION.match(instruction) and (match := _DESTINATION.match(instruction)):
            written.append((match[1], None))
        written += [(pointer, None) for pointer in _POST_MODIFY.findall(instruction)]
    for location, value in written:
        if location == 'sp':
            if frame.parent:
                return f'the stack pointer moves inside a loop at depth {frame.loop.depth}.'
            frame.values = {k: v for k, v in frame.values.items() if not k.startswith('sp')}
        elif frame.counter is not None and location == frame.counter:
            return f'loop counter {location} at depth {frame.loop.depth} is written again in its loop.'
        else:
            frame.set(location, value)
    if counter is not None:
        frame.counter = counter
    return None


def _resolve(value, seen=frozenset()) -> Optional[int]:
    """The immediate `value` always is. A value carried into an iteration of a loop is the loop's entry value on the
    first iteration and what the previous iteration left on the others: both must be the same immediate."""
    if not isinstance(value, _Carried):
        return value
    if value in seen:
        return None
    first = _resolve(value.frame.at_entry(value.location), seen | {value})
    left = value.frame.values.get(value.location, value)
    if left != value and _resolve(left, seen | {value}) != first:
        return None
    return first
